// AUTOGENERATED FILE FROM png2asset
//  Conversion args: /menu_level_selector.png -map

#ifndef METASPRITE_menu_level_selector_H
#define METASPRITE_menu_level_selector_H

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

#define menu_level_selector_TILE_ORIGIN 0
#define menu_level_selector_TILE_W 8
#define menu_level_selector_TILE_H 8
#define menu_level_selector_WIDTH 112
#define menu_level_selector_HEIGHT 80
#define menu_level_selector_TILE_COUNT 5
#define menu_level_selector_PALETTE_COUNT 1
#define menu_level_selector_COLORS_PER_PALETTE 4
#define menu_level_selector_TOTAL_COLORS 4
#define menu_level_selector_MAP_ATTRIBUTES 0
extern const unsigned char menu_level_selector_map[140];
#define menu_level_selector_map_attributes menu_level_selector_map

BANKREF_EXTERN(menu_level_selector)

extern const palette_color_t menu_level_selector_palettes[4];
extern const uint8_t menu_level_selector_tiles[80];

#endif
