// AUTOGENERATED FILE FROM png2asset
//  Conversion args: /menu_background.png -map -use_map_attributes

#ifndef METASPRITE_menu_background_H
#define METASPRITE_menu_background_H

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

#define menu_background_TILE_ORIGIN 0
#define menu_background_TILE_W 8
#define menu_background_TILE_H 8
#define menu_background_WIDTH 160
#define menu_background_HEIGHT 144
#define menu_background_TILE_COUNT 19
#define menu_background_PALETTE_COUNT 2
#define menu_background_COLORS_PER_PALETTE 4
#define menu_background_TOTAL_COLORS 8
#define menu_background_MAP_ATTRIBUTES menu_background_map_attributes
#define menu_background_MAP_ATTRIBUTES_WIDTH 20
#define menu_background_MAP_ATTRIBUTES_HEIGHT 18
#define menu_background_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define menu_background_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char menu_background_map[360];
extern const unsigned char menu_background_map_attributes[360];

BANKREF_EXTERN(menu_background)

extern const palette_color_t menu_background_palettes[8];
extern const uint8_t menu_background_tiles[304];

#endif
