// AUTOGENERATED FILE FROM png2asset
//  Conversion args: /menu_background.png -map

#ifndef METASPRITE_menu_background_H
#define METASPRITE_menu_background_H

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

#define menu_background_TILE_ORIGIN 0
#define menu_background_TILE_W 8
#define menu_background_TILE_H 8
#define menu_background_WIDTH 160
#define menu_background_HEIGHT 144
#define menu_background_TILE_COUNT 16
#define menu_background_PALETTE_COUNT 1
#define menu_background_COLORS_PER_PALETTE 4
#define menu_background_TOTAL_COLORS 4
#define menu_background_MAP_ATTRIBUTES 0
extern const unsigned char menu_background_map[360];
#define menu_background_map_attributes menu_background_map

BANKREF_EXTERN(menu_background)

extern const palette_color_t menu_background_palettes[4];
extern const uint8_t menu_background_tiles[256];

#endif
