// AUTOGENERATED FILE FROM png2asset
//  Conversion args: /orochi_jp_16x16.png -spr8x16 -sw 16 -sh 16
//  -sprite_no_optimize

#ifndef METASPRITE_orochi_jp_16x16_H
#define METASPRITE_orochi_jp_16x16_H

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

#define orochi_jp_16x16_TILE_ORIGIN 0
#define orochi_jp_16x16_TILE_W 8
#define orochi_jp_16x16_TILE_H 16
#define orochi_jp_16x16_WIDTH 16
#define orochi_jp_16x16_HEIGHT 16
#define orochi_jp_16x16_TILE_COUNT 8
#define orochi_jp_16x16_PALETTE_COUNT 1
#define orochi_jp_16x16_COLORS_PER_PALETTE 4
#define orochi_jp_16x16_TOTAL_COLORS 4
#define orochi_jp_16x16_PIVOT_X 8
#define orochi_jp_16x16_PIVOT_Y 8
#define orochi_jp_16x16_PIVOT_W 16
#define orochi_jp_16x16_PIVOT_H 16
extern const metasprite_t *const orochi_jp_16x16_metasprites[2];

BANKREF_EXTERN(orochi_jp_16x16)

extern const palette_color_t orochi_jp_16x16_palettes[4];
extern const uint8_t orochi_jp_16x16_tiles[128];

#endif
