// AUTOGENERATED FILE FROM png2asset
//  Conversion args: /yarara_font.png -spr8x8

#ifndef METASPRITE_yarara_font_H
#define METASPRITE_yarara_font_H

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

#define yarara_font_TILE_ORIGIN 0
#define yarara_font_TILE_W 8
#define yarara_font_TILE_H 8
#define yarara_font_WIDTH 200
#define yarara_font_HEIGHT 16
#define yarara_font_TILE_COUNT 44
#define yarara_font_PALETTE_COUNT 1
#define yarara_font_COLORS_PER_PALETTE 4
#define yarara_font_TOTAL_COLORS 4
#define yarara_font_PIVOT_X 100
#define yarara_font_PIVOT_Y 8
#define yarara_font_PIVOT_W 200
#define yarara_font_PIVOT_H 16
extern const metasprite_t *const yarara_font_metasprites[1];

BANKREF_EXTERN(yarara_font)

extern const palette_color_t yarara_font_palettes[4];
extern const uint8_t yarara_font_tiles[704];

#endif
