// AUTOGENERATED FILE FROM png2asset
//  Conversion args: /yarara_font_8x8.png -spr8x8 -sw 8 -sh 8
//  -sprite_no_optimize

#ifndef METASPRITE_yarara_font_8x8_H
#define METASPRITE_yarara_font_8x8_H

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

#define yarara_font_8x8_TILE_ORIGIN 0
#define yarara_font_8x8_TILE_W 8
#define yarara_font_8x8_TILE_H 8
#define yarara_font_8x8_WIDTH 8
#define yarara_font_8x8_HEIGHT 8
#define yarara_font_8x8_TILE_COUNT 90
#define yarara_font_8x8_PALETTE_COUNT 1
#define yarara_font_8x8_COLORS_PER_PALETTE 4
#define yarara_font_8x8_TOTAL_COLORS 4
#define yarara_font_8x8_PIVOT_X 4
#define yarara_font_8x8_PIVOT_Y 4
#define yarara_font_8x8_PIVOT_W 8
#define yarara_font_8x8_PIVOT_H 8
extern const metasprite_t *const yarara_font_8x8_metasprites[90];

BANKREF_EXTERN(yarara_font_8x8)

extern const palette_color_t yarara_font_8x8_palettes[4];
extern const uint8_t yarara_font_8x8_tiles[1440];

#endif
